/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedFollowingRouteImport } from './routes/_authenticated.following'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated.wallet'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CreatorsUsernameRouteImport } from './routes/creators.$username'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as AuthenticatedPlayIndexRouteImport } from './routes/_authenticated/play.index'
import { Route as AuthenticatedPlayIdRouteImport } from './routes/_authenticated/play.$id'
import { Route as AuthenticatedPlayNewRouteImport } from './routes/_authenticated/play.new'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated.studio.index'
import { Route as AuthenticatedStudioEarningsRouteImport } from './routes/_authenticated.studio.earnings'
import { Route as AuthenticatedStudioModerationRouteImport } from './routes/_authenticated.studio.moderation'
import { Route as AuthenticatedStudioSubscribersRouteImport } from './routes/_authenticated.studio.subscribers'
import { Route as BooksSlugReadRouteImport } from './routes/books.$slug.read'
import { Route as CreatorsUsernameIndexRouteImport } from './routes/creators.$username.index'
import { Route as CreatorsUsernameAchievementsRouteImport } from './routes/creators.$username.achievements'
import { Route as SeriesSlugIndexRouteImport } from './routes/series.$slug.index'
import { Route as SeriesSlugBibleRouteImport } from './routes/series.$slug.bible'
import { Route as SeriesSlugBooksRouteImport } from './routes/series.$slug.books'
import { Route as SeriesSlugLineageRouteImport } from './routes/series.$slug.lineage'
import { Route as AuthenticatedStudioSeriesNewRouteImport } from './routes/_authenticated.studio.series.new'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedStudioChaptersSlugEditRouteImport } from './routes/_authenticated.studio.chapters.$slug.edit'
import { Route as AuthenticatedStudioSeriesSlugBibleRouteImport } from './routes/_authenticated.studio.series.$slug.bible'
import { Route as AuthenticatedStudioSeriesSlugEditRouteImport } from './routes/_authenticated.studio.series.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFollowingRoute = AuthenticatedFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsUsernameRoute = CreatorsUsernameRouteImport.update({
  id: '/creators/$username',
  path: '/creators/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayIndexRoute = AuthenticatedPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayIdRoute = AuthenticatedPlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayNewRoute = AuthenticatedPlayNewRouteImport.update({
  id: '/play/new',
  path: '/play/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioEarningsRoute =
  AuthenticatedStudioEarningsRouteImport.update({
    id: '/studio/earnings',
    path: '/studio/earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioModerationRoute =
  AuthenticatedStudioModerationRouteImport.update({
    id: '/studio/moderation',
    path: '/studio/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioSubscribersRoute =
  AuthenticatedStudioSubscribersRouteImport.update({
    id: '/studio/subscribers',
    path: '/studio/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BooksSlugReadRoute = BooksSlugReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => BooksSlugRoute,
} as any)
const CreatorsUsernameIndexRoute = CreatorsUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorsUsernameRoute,
} as any)
const CreatorsUsernameAchievementsRoute =
  CreatorsUsernameAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => CreatorsUsernameRoute,
  } as any)
const SeriesSlugIndexRoute = SeriesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeriesSlugRoute,
} as any)
const SeriesSlugBibleRoute = SeriesSlugBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => SeriesSlugRoute,
} as any)
const SeriesSlugBooksRoute = SeriesSlugBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => SeriesSlugRoute,
} as any)
const SeriesSlugLineageRoute = SeriesSlugLineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => SeriesSlugRoute,
} as any)
const AuthenticatedStudioSeriesNewRoute =
  AuthenticatedStudioSeriesNewRouteImport.update({
    id: '/studio/series/new',
    path: '/studio/series/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStudioChaptersSlugEditRoute =
  AuthenticatedStudioChaptersSlugEditRouteImport.update({
    id: '/studio/chapters/$slug/edit',
    path: '/studio/chapters/$slug/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioSeriesSlugBibleRoute =
  AuthenticatedStudioSeriesSlugBibleRouteImport.update({
    id: '/studio/series/$slug/bible',
    path: '/studio/series/$slug/bible',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioSeriesSlugEditRoute =
  AuthenticatedStudioSeriesSlugEditRouteImport.update({
    id: '/studio/series/$slug/edit',
    path: '/studio/series/$slug/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/pricing': typeof PricingRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/creators/$username': typeof CreatorsUsernameRouteWithChildren
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/play/$id': typeof AuthenticatedPlayIdRoute
  '/play/new': typeof AuthenticatedPlayNewRoute
  '/studio/earnings': typeof AuthenticatedStudioEarningsRoute
  '/studio/moderation': typeof AuthenticatedStudioModerationRoute
  '/studio/subscribers': typeof AuthenticatedStudioSubscribersRoute
  '/books/$slug/read': typeof BooksSlugReadRoute
  '/creators/$username/achievements': typeof CreatorsUsernameAchievementsRoute
  '/series/$slug/bible': typeof SeriesSlugBibleRoute
  '/series/$slug/books': typeof SeriesSlugBooksRoute
  '/series/$slug/lineage': typeof SeriesSlugLineageRoute
  '/play/': typeof AuthenticatedPlayIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/creators/$username/': typeof CreatorsUsernameIndexRoute
  '/series/$slug/': typeof SeriesSlugIndexRoute
  '/studio/series/new': typeof AuthenticatedStudioSeriesNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/studio/chapters/$slug/edit': typeof AuthenticatedStudioChaptersSlugEditRoute
  '/studio/series/$slug/bible': typeof AuthenticatedStudioSeriesSlugBibleRoute
  '/studio/series/$slug/edit': typeof AuthenticatedStudioSeriesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/pricing': typeof PricingRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
  '/play/new': typeof AuthenticatedPlayNewRoute
  '/studio/earnings': typeof AuthenticatedStudioEarningsRoute
  '/studio/moderation': typeof AuthenticatedStudioModerationRoute
  '/studio/subscribers': typeof AuthenticatedStudioSubscribersRoute
  '/books/$slug/read': typeof BooksSlugReadRoute
  '/creators/$username/achievements': typeof CreatorsUsernameAchievementsRoute
  '/series/$slug/bible': typeof SeriesSlugBibleRoute
  '/series/$slug/books': typeof SeriesSlugBooksRoute
  '/series/$slug/lineage': typeof SeriesSlugLineageRoute
  '/play': typeof AuthenticatedPlayIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/creators/$username': typeof CreatorsUsernameIndexRoute
  '/series/$slug': typeof SeriesSlugIndexRoute
  '/studio/series/new': typeof AuthenticatedStudioSeriesNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/studio/chapters/$slug/edit': typeof AuthenticatedStudioChaptersSlugEditRoute
  '/studio/series/$slug/bible': typeof AuthenticatedStudioSeriesSlugBibleRoute
  '/studio/series/$slug/edit': typeof AuthenticatedStudioSeriesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/following': typeof AuthenticatedFollowingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/creators/$username': typeof CreatorsUsernameRouteWithChildren
  '/series/$slug': typeof SeriesSlugRouteWithChildren
  '/_authenticated/play/$id': typeof AuthenticatedPlayIdRoute
  '/_authenticated/play/new': typeof AuthenticatedPlayNewRoute
  '/_authenticated/studio/earnings': typeof AuthenticatedStudioEarningsRoute
  '/_authenticated/studio/moderation': typeof AuthenticatedStudioModerationRoute
  '/_authenticated/studio/subscribers': typeof AuthenticatedStudioSubscribersRoute
  '/books/$slug/read': typeof BooksSlugReadRoute
  '/creators/$username/achievements': typeof CreatorsUsernameAchievementsRoute
  '/series/$slug/bible': typeof SeriesSlugBibleRoute
  '/series/$slug/books': typeof SeriesSlugBooksRoute
  '/series/$slug/lineage': typeof SeriesSlugLineageRoute
  '/_authenticated/play/': typeof AuthenticatedPlayIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/creators/$username/': typeof CreatorsUsernameIndexRoute
  '/series/$slug/': typeof SeriesSlugIndexRoute
  '/_authenticated/studio/series/new': typeof AuthenticatedStudioSeriesNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/studio/chapters/$slug/edit': typeof AuthenticatedStudioChaptersSlugEditRoute
  '/_authenticated/studio/series/$slug/bible': typeof AuthenticatedStudioSeriesSlugBibleRoute
  '/_authenticated/studio/series/$slug/edit': typeof AuthenticatedStudioSeriesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/pricing'
    | '/following'
    | '/notifications'
    | '/onboarding'
    | '/wallet'
    | '/books/$slug'
    | '/chapters/$slug'
    | '/checkout/success'
    | '/creators/$username'
    | '/series/$slug'
    | '/play/$id'
    | '/play/new'
    | '/studio/earnings'
    | '/studio/moderation'
    | '/studio/subscribers'
    | '/books/$slug/read'
    | '/creators/$username/achievements'
    | '/series/$slug/bible'
    | '/series/$slug/books'
    | '/series/$slug/lineage'
    | '/play/'
    | '/studio/'
    | '/creators/$username/'
    | '/series/$slug/'
    | '/studio/series/new'
    | '/api/public/payments/webhook'
    | '/studio/chapters/$slug/edit'
    | '/studio/series/$slug/bible'
    | '/studio/series/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/pricing'
    | '/following'
    | '/notifications'
    | '/onboarding'
    | '/wallet'
    | '/books/$slug'
    | '/chapters/$slug'
    | '/checkout/success'
    | '/play/$id'
    | '/play/new'
    | '/studio/earnings'
    | '/studio/moderation'
    | '/studio/subscribers'
    | '/books/$slug/read'
    | '/creators/$username/achievements'
    | '/series/$slug/bible'
    | '/series/$slug/books'
    | '/series/$slug/lineage'
    | '/play'
    | '/studio'
    | '/creators/$username'
    | '/series/$slug'
    | '/studio/series/new'
    | '/api/public/payments/webhook'
    | '/studio/chapters/$slug/edit'
    | '/studio/series/$slug/bible'
    | '/studio/series/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/pricing'
    | '/_authenticated/following'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/wallet'
    | '/books/$slug'
    | '/chapters/$slug'
    | '/checkout/success'
    | '/creators/$username'
    | '/series/$slug'
    | '/_authenticated/play/$id'
    | '/_authenticated/play/new'
    | '/_authenticated/studio/earnings'
    | '/_authenticated/studio/moderation'
    | '/_authenticated/studio/subscribers'
    | '/books/$slug/read'
    | '/creators/$username/achievements'
    | '/series/$slug/bible'
    | '/series/$slug/books'
    | '/series/$slug/lineage'
    | '/_authenticated/play/'
    | '/_authenticated/studio/'
    | '/creators/$username/'
    | '/series/$slug/'
    | '/_authenticated/studio/series/new'
    | '/api/public/payments/webhook'
    | '/_authenticated/studio/chapters/$slug/edit'
    | '/_authenticated/studio/series/$slug/bible'
    | '/_authenticated/studio/series/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  PricingRoute: typeof PricingRoute
  BooksSlugRoute: typeof BooksSlugRouteWithChildren
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CreatorsUsernameRoute: typeof CreatorsUsernameRouteWithChildren
  SeriesSlugRoute: typeof SeriesSlugRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/following': {
      id: '/_authenticated/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AuthenticatedFollowingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$username': {
      id: '/creators/$username'
      path: '/creators/$username'
      fullPath: '/creators/$username'
      preLoaderRoute: typeof CreatorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/play/': {
      id: '/_authenticated/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof AuthenticatedPlayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$id': {
      id: '/_authenticated/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof AuthenticatedPlayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/new': {
      id: '/_authenticated/play/new'
      path: '/play/new'
      fullPath: '/play/new'
      preLoaderRoute: typeof AuthenticatedPlayNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/earnings': {
      id: '/_authenticated/studio/earnings'
      path: '/studio/earnings'
      fullPath: '/studio/earnings'
      preLoaderRoute: typeof AuthenticatedStudioEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/moderation': {
      id: '/_authenticated/studio/moderation'
      path: '/studio/moderation'
      fullPath: '/studio/moderation'
      preLoaderRoute: typeof AuthenticatedStudioModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/subscribers': {
      id: '/_authenticated/studio/subscribers'
      path: '/studio/subscribers'
      fullPath: '/studio/subscribers'
      preLoaderRoute: typeof AuthenticatedStudioSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/books/$slug/read': {
      id: '/books/$slug/read'
      path: '/read'
      fullPath: '/books/$slug/read'
      preLoaderRoute: typeof BooksSlugReadRouteImport
      parentRoute: typeof BooksSlugRoute
    }
    '/creators/$username/': {
      id: '/creators/$username/'
      path: '/'
      fullPath: '/creators/$username/'
      preLoaderRoute: typeof CreatorsUsernameIndexRouteImport
      parentRoute: typeof CreatorsUsernameRoute
    }
    '/creators/$username/achievements': {
      id: '/creators/$username/achievements'
      path: '/achievements'
      fullPath: '/creators/$username/achievements'
      preLoaderRoute: typeof CreatorsUsernameAchievementsRouteImport
      parentRoute: typeof CreatorsUsernameRoute
    }
    '/series/$slug/': {
      id: '/series/$slug/'
      path: '/'
      fullPath: '/series/$slug/'
      preLoaderRoute: typeof SeriesSlugIndexRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
    '/series/$slug/bible': {
      id: '/series/$slug/bible'
      path: '/bible'
      fullPath: '/series/$slug/bible'
      preLoaderRoute: typeof SeriesSlugBibleRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
    '/series/$slug/books': {
      id: '/series/$slug/books'
      path: '/books'
      fullPath: '/series/$slug/books'
      preLoaderRoute: typeof SeriesSlugBooksRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
    '/series/$slug/lineage': {
      id: '/series/$slug/lineage'
      path: '/lineage'
      fullPath: '/series/$slug/lineage'
      preLoaderRoute: typeof SeriesSlugLineageRouteImport
      parentRoute: typeof SeriesSlugRoute
    }
    '/_authenticated/studio/series/new': {
      id: '/_authenticated/studio/series/new'
      path: '/studio/series/new'
      fullPath: '/studio/series/new'
      preLoaderRoute: typeof AuthenticatedStudioSeriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/chapters/$slug/edit': {
      id: '/_authenticated/studio/chapters/$slug/edit'
      path: '/studio/chapters/$slug/edit'
      fullPath: '/studio/chapters/$slug/edit'
      preLoaderRoute: typeof AuthenticatedStudioChaptersSlugEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/series/$slug/bible': {
      id: '/_authenticated/studio/series/$slug/bible'
      path: '/studio/series/$slug/bible'
      fullPath: '/studio/series/$slug/bible'
      preLoaderRoute: typeof AuthenticatedStudioSeriesSlugBibleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/series/$slug/edit': {
      id: '/_authenticated/studio/series/$slug/edit'
      path: '/studio/series/$slug/edit'
      fullPath: '/studio/series/$slug/edit'
      preLoaderRoute: typeof AuthenticatedStudioSeriesSlugEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFollowingRoute: typeof AuthenticatedFollowingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedPlayIdRoute: typeof AuthenticatedPlayIdRoute
  AuthenticatedPlayNewRoute: typeof AuthenticatedPlayNewRoute
  AuthenticatedStudioEarningsRoute: typeof AuthenticatedStudioEarningsRoute
  AuthenticatedStudioModerationRoute: typeof AuthenticatedStudioModerationRoute
  AuthenticatedStudioSubscribersRoute: typeof AuthenticatedStudioSubscribersRoute
  AuthenticatedPlayIndexRoute: typeof AuthenticatedPlayIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
  AuthenticatedStudioSeriesNewRoute: typeof AuthenticatedStudioSeriesNewRoute
  AuthenticatedStudioChaptersSlugEditRoute: typeof AuthenticatedStudioChaptersSlugEditRoute
  AuthenticatedStudioSeriesSlugBibleRoute: typeof AuthenticatedStudioSeriesSlugBibleRoute
  AuthenticatedStudioSeriesSlugEditRoute: typeof AuthenticatedStudioSeriesSlugEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFollowingRoute: AuthenticatedFollowingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedPlayIdRoute: AuthenticatedPlayIdRoute,
  AuthenticatedPlayNewRoute: AuthenticatedPlayNewRoute,
  AuthenticatedStudioEarningsRoute: AuthenticatedStudioEarningsRoute,
  AuthenticatedStudioModerationRoute: AuthenticatedStudioModerationRoute,
  AuthenticatedStudioSubscribersRoute: AuthenticatedStudioSubscribersRoute,
  AuthenticatedPlayIndexRoute: AuthenticatedPlayIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
  AuthenticatedStudioSeriesNewRoute: AuthenticatedStudioSeriesNewRoute,
  AuthenticatedStudioChaptersSlugEditRoute:
    AuthenticatedStudioChaptersSlugEditRoute,
  AuthenticatedStudioSeriesSlugBibleRoute:
    AuthenticatedStudioSeriesSlugBibleRoute,
  AuthenticatedStudioSeriesSlugEditRoute:
    AuthenticatedStudioSeriesSlugEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BooksSlugRouteChildren {
  BooksSlugReadRoute: typeof BooksSlugReadRoute
}

const BooksSlugRouteChildren: BooksSlugRouteChildren = {
  BooksSlugReadRoute: BooksSlugReadRoute,
}

const BooksSlugRouteWithChildren = BooksSlugRoute._addFileChildren(
  BooksSlugRouteChildren,
)

interface CreatorsUsernameRouteChildren {
  CreatorsUsernameAchievementsRoute: typeof CreatorsUsernameAchievementsRoute
  CreatorsUsernameIndexRoute: typeof CreatorsUsernameIndexRoute
}

const CreatorsUsernameRouteChildren: CreatorsUsernameRouteChildren = {
  CreatorsUsernameAchievementsRoute: CreatorsUsernameAchievementsRoute,
  CreatorsUsernameIndexRoute: CreatorsUsernameIndexRoute,
}

const CreatorsUsernameRouteWithChildren =
  CreatorsUsernameRoute._addFileChildren(CreatorsUsernameRouteChildren)

interface SeriesSlugRouteChildren {
  SeriesSlugBibleRoute: typeof SeriesSlugBibleRoute
  SeriesSlugBooksRoute: typeof SeriesSlugBooksRoute
  SeriesSlugLineageRoute: typeof SeriesSlugLineageRoute
  SeriesSlugIndexRoute: typeof SeriesSlugIndexRoute
}

const SeriesSlugRouteChildren: SeriesSlugRouteChildren = {
  SeriesSlugBibleRoute: SeriesSlugBibleRoute,
  SeriesSlugBooksRoute: SeriesSlugBooksRoute,
  SeriesSlugLineageRoute: SeriesSlugLineageRoute,
  SeriesSlugIndexRoute: SeriesSlugIndexRoute,
}

const SeriesSlugRouteWithChildren = SeriesSlugRoute._addFileChildren(
  SeriesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  PricingRoute: PricingRoute,
  BooksSlugRoute: BooksSlugRouteWithChildren,
  ChaptersSlugRoute: ChaptersSlugRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CreatorsUsernameRoute: CreatorsUsernameRouteWithChildren,
  SeriesSlugRoute: SeriesSlugRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
