/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as CreatorsUsernameRouteImport } from './routes/creators.$username'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsUsernameRoute = CreatorsUsernameRouteImport.update({
  id: '/creators/$username',
  path: '/creators/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/books/$slug': typeof BooksSlugRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/series/$slug': typeof SeriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/books/$slug': typeof BooksSlugRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/series/$slug': typeof SeriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/books/$slug': typeof BooksSlugRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/series/$slug': typeof SeriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/books/$slug'
    | '/chapters/$slug'
    | '/creators/$username'
    | '/series/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/books/$slug'
    | '/chapters/$slug'
    | '/creators/$username'
    | '/series/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/discover'
    | '/books/$slug'
    | '/chapters/$slug'
    | '/creators/$username'
    | '/series/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  BooksSlugRoute: typeof BooksSlugRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  CreatorsUsernameRoute: typeof CreatorsUsernameRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$username': {
      id: '/creators/$username'
      path: '/creators/$username'
      fullPath: '/creators/$username'
      preLoaderRoute: typeof CreatorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  BooksSlugRoute: BooksSlugRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  CreatorsUsernameRoute: CreatorsUsernameRoute,
  SeriesSlugRoute: SeriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
